            @100
            D=A 
            @R3
            D=D-M
            @MENOR
            @12
            D;JGT
            @R5
            M=1
            @END
            0;JMP
(MENOR)
            @R5
            M=0
(END)            
            @END
            0;JMP